### ISSUE TITLE
Error 503 Service not available - when restarting

### ISSUE THREAD

**Issue by ElKen1** [frontlinesms/frontlinesms2#6]
My environment is Windows 7 32bits.

After installing FrontlineSMS 2, it started smoothly and I was able to create a link to SMSSync. Unfortunately, after shutting down frontline, any attempt to restart the system leads to Error 503 Service Unavailable.
Below is the Stacktrace log.

Stacktrace.log
------------------------------
2015-09-24 08:12:28,038 [main] WARN  cfg.ConfigurationHelper  - Unable to load specified config location file:*****.frontlinesms2/log4j.groovy : File does not exist.
2015-09-24 08:12:36,938 [main] WARN  pool.ConnectionPool  - maxActive is smaller than 1, setting maxActive to: 100
2015-09-24 08:12:38,028 [main] WARN  util.GrailsUtil  - [WARNING] Property [inArchive] of domain class frontlinesms2.Search has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,028 [main] WARN  util.GrailsUtil  - [WARNING] Property [starredOnly] of domain class frontlinesms2.Search has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,059 [main] WARN  util.GrailsUtil  - [WARNING] Property [date] of domain class frontlinesms2.LogEntry has type [java.util.Date] and doesn't support constraint [blank]. This constraint will not be checked during validation.
2015-09-24 08:12:38,106 [main] WARN  util.GrailsUtil  - [WARNING] Property [sendEnabled] of domain class frontlinesms2.SmslibFconnection has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,106 [main] WARN  util.GrailsUtil  - [WARNING] Property [receiveEnabled] of domain class frontlinesms2.SmslibFconnection has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,153 [main] WARN  util.GrailsUtil  - [WARNING] Property [recipeToTriggerId] of domain class frontlinesms2.TriggerRecipeAction has type [long] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,293 [main] WARN  util.GrailsUtil  - [WARNING] Property [recipeToTriggerId] of domain class frontlinesms2.TriggerRecipeActionEvent has type [long] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.Interaction has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.TextMessage has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,325 [main] WARN  util.GrailsUtil  - [WARNING] Property [inbound] of domain class frontlinesms2.TextMessage has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.FireTrigger has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.FireTrigger has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.OutboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:38,340 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.OutboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:12:51,356 [main] WARN  injection.Injection  - Could not inject method displayMessage(java.util.Map) in to [org.grails.plugin.platform.UiExtensionsTagLib], a method with that name and argument list already exists
2015-09-24 08:13:06,715 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.APIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.APIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.api.APIRequest will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.api.APIRequest will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.api.APIRequest will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.InboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.OutboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,731 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.api.OutboundAPIRequest has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.FireTrigger has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.FireTrigger has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.FireTrigger will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.Interaction has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.Interaction will not be checked during validation.
2015-09-24 08:13:06,746 [main] WARN  util.GrailsUtil  - [WARNING] Property [date] of domain class frontlinesms2.LogEntry has type [java.util.Date] and doesn't support constraint [blank]. This constraint will not be checked during validation.
2015-09-24 08:13:06,762 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.MissedCall has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,762 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.MissedCall will not be checked during validation.
2015-09-24 08:13:06,762 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.MissedCall will not be checked during validation.
2015-09-24 08:13:06,762 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.MissedCall will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [inArchive] of domain class frontlinesms2.Search has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [starredOnly] of domain class frontlinesms2.Search has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [sendEnabled] of domain class frontlinesms2.SmslibFconnection has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [receiveEnabled] of domain class frontlinesms2.SmslibFconnection has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [archived] of domain class frontlinesms2.TextMessage has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [inbound] of domain class frontlinesms2.TextMessage has type [boolean] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [inboundContactName] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [outboundContactName] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  validation.DefaultConstraintEvaluator  - Derived properties may not be constrained. Property [type] of domain class frontlinesms2.TextMessage will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [recipeToTriggerId] of domain class frontlinesms2.TriggerRecipeAction has type [long] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:06,778 [main] WARN  util.GrailsUtil  - [WARNING] Property [recipeToTriggerId] of domain class frontlinesms2.TriggerRecipeActionEvent has type [long] and doesn't support constraint [nullable]. This constraint will not be checked during validation.
2015-09-24 08:13:08,184 [main] WARN  util.JDBCExceptionReporter  - SQL Error: 23505, SQLState: 23505
2015-09-24 08:13:08,184 [main] ERROR util.JDBCExceptionReporter  - Unique index or primary key violation: "CONSTRAINT_87_INDEX_7 ON PUBLIC.SYSTEM_NOTIFICATION(TEXT)"; SQL statement:
insert into system_notification (id, version, rd, severity, text, topic) values (null, ?, ?, ?, ?, ?) [23505-164]
2015-09-24 08:13:08,231 [main] WARN  frontlinesms2.FconnectionService  - Error creating routes to fconnection with id frontlinesms2.SmssyncFconnection : 1?.id
org.springframework.dao.DataIntegrityViolationException: could not insert: [frontlinesms2.SystemNotification]; SQL [insert into system_notification (id, version, rd, severity, text, topic) values (null, ?, ?, ?, ?, ?)]; constraint ["CONSTRAINT_87_INDEX_7 ON PUBLIC.SYSTEM_NOTIFICATION(TEXT)"; SQL statement:
insert into system_notification (id, version, rd, severity, text, topic) values (null, ?, ?, ?, ?, ?) [23505-164]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [frontlinesms2.SystemNotification]
	at frontlinesms2.SystemNotificationService.getOrCreate(SystemNotificationService.groovy:34)
	at frontlinesms2.SystemNotificationService.create(SystemNotificationService.groovy:16)
	at frontlinesms2.FconnectionService.createRoutes(FconnectionService.groovy:35)
	at CoreBootStrap$_initialiseNonSmslibFconnections_closure21.doCall(CoreBootStrap.groovy:951)
	at CoreBootStrap.initialiseNonSmslibFconnections(CoreBootStrap.groovy:948)
	at CoreBootStrap$_closure1.doCall(CoreBootStrap.groovy:126)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:672)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:664)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:239)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1212)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:610)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:453)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at net.frontlinesms2.systraymonitor.Monitor.start(Monitor.java:35)
	at net.frontlinesms2.systraymonitor.Main.init(Main.java:135)
	at net.frontlinesms2.systraymonitor.Main.main(Main.java:57)
Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [frontlinesms2.SystemNotification]
	... 23 more
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "CONSTRAINT_87_INDEX_7 ON PUBLIC.SYSTEM_NOTIFICATION(TEXT)"; SQL statement:
insert into system_notification (id, version, rd, severity, text, topic) values (null, ?, ?, ?, ?, ?) [23505-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:81)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:146)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:100)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:105)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:96)
	at org.h2.index.MultiVersionIndex.add(MultiVersionIndex.java:50)
	at org.h2.table.RegularTable.addRow(RegularTable.java:121)
	at org.h2.command.dml.Insert.insertRows(Insert.java:124)
	at org.h2.command.dml.Insert.update(Insert.java:84)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129)
	... 23 more
2015-09-24 08:13:08,278 [main] ERROR hibernate.AssertionFailure  - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: null id in frontlinesms2.SystemNotification entry (don't flush the Session after an exception occurs)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:101)
	at frontlinesms2.SystemNotificationService.getOrCreate(SystemNotificationService.groovy:23)
	at frontlinesms2.SystemNotificationService.create(SystemNotificationService.groovy:16)
	at frontlinesms2.FconnectionService.logFail(FconnectionService.groovy:159)
	at frontlinesms2.FconnectionService.createRoutes(FconnectionService.groovy:40)
	at CoreBootStrap$_initialiseNonSmslibFconnections_closure21.doCall(CoreBootStrap.groovy:951)
	at CoreBootStrap.initialiseNonSmslibFconnections(CoreBootStrap.groovy:948)
	at CoreBootStrap$_closure1.doCall(CoreBootStrap.groovy:126)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:672)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:664)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:239)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1212)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:610)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:453)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at net.frontlinesms2.systraymonitor.Monitor.start(Monitor.java:35)
	at net.frontlinesms2.systraymonitor.Main.init(Main.java:135)
	at net.frontlinesms2.systraymonitor.Main.main(Main.java:57)
2015-09-24 08:13:08,293 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: null id in frontlinesms2.SystemNotification entry (don't flush the Session after an exception occurs)
org.hibernate.AssertionFailure: null id in frontlinesms2.SystemNotification entry (don't flush the Session after an exception occurs)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:101)
	at frontlinesms2.SystemNotificationService.getOrCreate(SystemNotificationService.groovy:23)
	at frontlinesms2.SystemNotificationService.create(SystemNotificationService.groovy:16)
	at frontlinesms2.FconnectionService.logFail(FconnectionService.groovy:159)
	at frontlinesms2.FconnectionService.createRoutes(FconnectionService.groovy:40)
	at CoreBootStrap$_initialiseNonSmslibFconnections_closure21.doCall(CoreBootStrap.groovy:951)
	at CoreBootStrap.initialiseNonSmslibFconnections(CoreBootStrap.groovy:948)
	at CoreBootStrap$_closure1.doCall(CoreBootStrap.groovy:126)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:672)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:664)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:239)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1212)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:610)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:453)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at net.frontlinesms2.systraymonitor.Monitor.start(Monitor.java:35)
	at net.frontlinesms2.systraymonitor.Main.init(Main.java:135)
	at net.frontlinesms2.systraymonitor.Main.main(Main.java:57)
2015-09-24 08:13:08,293 [main] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: null id in frontlinesms2.SystemNotification entry (don't flush the Session after an exception occurs)
org.hibernate.AssertionFailure: null id in frontlinesms2.SystemNotification entry (don't flush the Session after an exception occurs)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:101)
	at frontlinesms2.SystemNotificationService.getOrCreate(SystemNotificationService.groovy:23)
	at frontlinesms2.SystemNotificationService.create(SystemNotificationService.groovy:16)
	at frontlinesms2.FconnectionService.logFail(FconnectionService.groovy:159)
	at frontlinesms2.FconnectionService.createRoutes(FconnectionService.groovy:40)
	at CoreBootStrap$_initialiseNonSmslibFconnections_closure21.doCall(CoreBootStrap.groovy:951)
	at CoreBootStrap.initialiseNonSmslibFconnections(CoreBootStrap.groovy:948)
	at CoreBootStrap$_closure1.doCall(CoreBootStrap.groovy:126)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:672)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:664)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:239)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1212)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:610)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:453)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at net.frontlinesms2.systraymonitor.Monitor.start(Monitor.java:35)
	at net.frontlinesms2.systraymonitor.Main.init(Main.java:135)
	at net.frontlinesms2.systraymonitor.Main.main(Main.java:57)

**Comment by lesiki** [comment]
Hi @ElKen1, thanks for reporting this, I'm looking into it at the moment. Did you have a previous version of FrontlineSMS installed before you tried 2.6.3?

**Comment by ElKen1** [comment]
Hi, I had the 2.6.2 version and was having the same problem before switching to the recent version. Unfortunately the same issues are there. I deleted the .frontlinesms2 folder but for no success.

**Comment by ElKen1** [comment]
I even thought that it was related to computer. I changed to another computer running Win7 and same issues.

**Comment by lesiki** [comment]
Thanks for the update. So was every attempt the same: you would install fine, then add a connection, restart the app and it fails on startup?

The exception is being thrown when attempting to notify you that your saved connection has been automatically reconnected on startup. If all you have in your database is the saved connection, do you mind sharing it with us? Just zip up the whole .frontlinesms2 folder and email to support at frontlinesms dot com.
